force-app/main/default/objects/Contribution__c/Contribution__c.object-meta.xml
<CustomObject>
    <label>Contribution</label>
    <nameField>
        <displayFormat>CON-{0000}</displayFormat>
        <label>Contribution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contribution__c/fields/Contributor__c.field-meta.xml
<CustomField>
    <fullName>Contributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contributor</label>
    <referenceTo>Contributor__c</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Contributions</relationshipLabel>
    <relationshipName>Contributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contribution__c/fields/Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Review_Status__c</fullName>
    <label>Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Changes Requested</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contributor__c/Contributor__c.object-meta.xml
<CustomObject>
    <label>Contributor</label>
    <nameField>
        <label>Contributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <label>Repository</label>
    <referenceTo>Repository__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Active_Contributors__c.field-meta.xml
<CustomField>
    <fullName>Active_Contributors__c</fullName>
    <label>Active Contributors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Technology_Stack__c.field-meta.xml
<CustomField>
    <fullName>Technology_Stack__c</fullName>
    <label>Technology Stack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organization__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrganizationService.cls
public with sharing class OrganizationService {

    // Returns all organizations
    public static List<Organization__c> getOrganizations(){

        return [

            SELECT Id,
                   Name,
                   Active__c,
                   Total_Repositories__c,
                   Active_Contributors__c,
                   Technology_Stack__c

            FROM Organization__c

            ORDER BY Name

        ];

    }

    // Updates Total Repositories
    public static void updateRepositoryCount(Id organizationId){

        if(organizationId == null){
            return;
        }

        Integer repoCount = [

            SELECT COUNT()

            FROM Repository__c

            WHERE Organization__c = :organizationId

        ];

        update new Organization__c(

            Id = organizationId,
            Total_Repositories__c = repoCount

        );

    }

    // Updates Active Contributors
    public static void updateActiveContributors(Id organizationId){

        if(organizationId == null){
            return;
        }

        Set<Id> contributorIds = new Set<Id>();

        List<Contribution__c> contributions = [

            SELECT Contributor__c

            FROM Contribution__c

            WHERE Review_Status__c IN ('Approved','Merged')
            AND Issue__r.Repository__r.Organization__c = :organizationId

        ];

        for(Contribution__c contribution : contributions){

            if(contribution.Contributor__c != null){

                contributorIds.add(contribution.Contributor__c);

            }

        }

        update new Organization__c(

            Id = organizationId,
            Active_Contributors__c = contributorIds.size()

        );

    }

}