force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <label>Repository</label>
    <referenceTo>Repository__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IssueTriggerHandler.cls
public with sharing class IssueTriggerHandler {

    public static void afterInsert(List<Issue__c> newIssues){

        Set<Id> repositoryIds = new Set<Id>();

        for(Issue__c issue : newIssues){

            if(issue.Repository__c != null){

                repositoryIds.add(issue.Repository__c);

            }

        }

        for(Id repoId : repositoryIds){

            RepositoryService.updateOpenIssues(repoId);

        }

    }

    public static void afterUpdate(
        List<Issue__c> newIssues,
        Map<Id, Issue__c> oldMap
    ){

        Set<Id> repositoryIds = new Set<Id>();

        for(Issue__c issue : newIssues){

            if(issue.Repository__c != null){

                repositoryIds.add(issue.Repository__c);

            }

            Issue__c oldIssue = oldMap.get(issue.Id);

            if(oldIssue.Repository__c != null){

                repositoryIds.add(oldIssue.Repository__c);

            }

        }

        for(Id repoId : repositoryIds){

            RepositoryService.updateOpenIssues(repoId);

        }

    }

    public static void afterDelete(List<Issue__c> oldIssues){

        Set<Id> repositoryIds = new Set<Id>();

        for(Issue__c issue : oldIssues){

            if(issue.Repository__c != null){

                repositoryIds.add(issue.Repository__c);

            }

        }

        for(Id repoId : repositoryIds){

            RepositoryService.updateOpenIssues(repoId);

        }

    }

}