force-app/main/default/objects/Badge__c/Badge__c.object-meta.xml
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge__c/fields/Awarded_Date__c.field-meta.xml
<CustomField>
    <fullName>Awarded_Date__c</fullName>
    <label>Awarded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Badge__c/fields/Badge_Type__c.field-meta.xml
<CustomField>
    <fullName>Badge_Type__c</fullName>
    <label>Badge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Contribution</fullName>
            </value>
            <value>
                <fullName>Top Contributor</fullName>
            </value>
            <value>
                <fullName>Bug Hunter</fullName>
            </value>
            <value>
                <fullName>Documentation Hero</fullName>
            </value>
            <value>
                <fullName>Code Reviewer</fullName>
            </value>
            <value>
                <fullName>Open Source Champion</fullName>
            </value>
            <value>
                <fullName>Mentor Choice</fullName>
            </value>
            <value>
                <fullName>Community Helper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Badge__c/fields/Contributor__c.field-meta.xml
<CustomField>
    <fullName>Contributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contributor</label>
    <referenceTo>Contributor__c</referenceTo>
    <relationshipLabel>Badges</relationshipLabel>
    <relationshipName>Badges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Badge__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contributor__c/Contributor__c.object-meta.xml
<CustomObject>
    <label>Contributor</label>
    <nameField>
        <label>Contributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contributor__c/fields/Reputation_Score__c.field-meta.xml
<CustomField>
    <fullName>Reputation_Score__c</fullName>
    <label>Reputation Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contributor__c/fields/Total_Contributions__c.field-meta.xml
<CustomField>
    <fullName>Total_Contributions__c</fullName>
    <label>Total Contributions</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BadgeService.cls
public with sharing class BadgeService {

    public static List<Badge__c> getBadges(){

        return [

            SELECT Id,
                   Name,
                   Badge_Type__c,
                   Points__c,
                   Awarded_Date__c,
                   Contributor__c

            FROM Badge__c

        ];

    }

    public static void awardBadges(Id contributorId){

        Contributor__c contributor = [

            SELECT Id,
                   Name,
                   Reputation_Score__c,
                   Total_Contributions__c

            FROM Contributor__c

            WHERE Id = :contributorId

            LIMIT 1

        ];

        List<Badge__c> existingBadges = [

            SELECT Name

            FROM Badge__c

            WHERE Contributor__c = :contributorId

        ];

        Set<String> earned = new Set<String>();

        for(Badge__c b : existingBadges){
            earned.add(b.Name);
        }

        List<Badge__c> newBadges = new List<Badge__c>();

        // First Contribution Badge
        if(contributor.Total_Contributions__c >= 1 &&
           !earned.contains('First Contribution')){

            newBadges.add(new Badge__c(

                Name='First Contribution',
                Contributor__c=contributor.Id,
                Badge_Type__c='First Contribution',
                Points__c=10,
                Awarded_Date__c=Date.today(),
                Active__c=true

            ));

        }

        // Top Contributor Badge
        if(contributor.Total_Contributions__c >= 5 &&
           !earned.contains('Top Contributor')){

            newBadges.add(new Badge__c(

                Name='Top Contributor',
                Contributor__c=contributor.Id,
                Badge_Type__c='Top Contributor',
                Points__c=50,
                Awarded_Date__c=Date.today(),
                Active__c=true

            ));

        }

        // Open Source Champion Badge
        if(contributor.Total_Contributions__c >= 25 &&
           !earned.contains('Open Source Champion')){

            newBadges.add(new Badge__c(

                Name='Open Source Champion',
                Contributor__c=contributor.Id,
                Badge_Type__c='Open Source Champion',
                Points__c=150,
                Awarded_Date__c=Date.today(),
                Active__c=true

            ));

        }

        if(contributor.Total_Contributions__c >= 50 &&
           !earned.contains('Community Helper')){

            newBadges.add(new Badge__c(

                Name='Community Helper',
                Contributor__c=contributor.Id,
                Badge_Type__c='Community Helper',
                Points__c=300,
                Awarded_Date__c=Date.today(),
                Active__c=true

            ));

        }

        if(!newBadges.isEmpty()){
            insert newBadges;
        }

    }

}