force-app/main/default/objects/Contributor__c/Contributor__c.object-meta.xml
<CustomObject>
    <label>Contributor</label>
    <nameField>
        <label>Contributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contributor__c/fields/Primary_Skill__c.field-meta.xml
<CustomField>
    <fullName>Primary_Skill__c</fullName>
    <label>Primary Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>HTML/CSS</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contributor__c/fields/Reputation_Score__c.field-meta.xml
<CustomField>
    <fullName>Reputation_Score__c</fullName>
    <label>Reputation Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContributorSOAPService.cls
global with sharing class ContributorSOAPService {

    webService static List<Contributor__c> getContributors() {

        return [
            SELECT Id,
                   Name,
                   Email__c,
                   Country__c,
                   Primary_Skill__c,
                   Reputation_Score__c
            FROM Contributor__c
        ];
    }

    webService static Contributor__c getContributor(Id contributorId) {

        return [
            SELECT Id,
                   Name,
                   Email__c,
                   Country__c,
                   Primary_Skill__c,
                   Reputation_Score__c
            FROM Contributor__c
            WHERE Id=:contributorId
            LIMIT 1
        ];
    }

}