force-app/main/default/objects/Contributor__c/Contributor__c.object-meta.xml
<CustomObject>
    <label>Contributor</label>
    <nameField>
        <label>Contributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contributor__c/fields/Current_Rank__c.field-meta.xml
<CustomField>
    <fullName>Current_Rank__c</fullName>
    <label>Current Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contributor__c/fields/Reputation_Score__c.field-meta.xml
<CustomField>
    <fullName>Reputation_Score__c</fullName>
    <label>Reputation Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contributor__c/fields/Total_Contributions__c.field-meta.xml
<CustomField>
    <fullName>Total_Contributions__c</fullName>
    <label>Total Contributions</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContributorService.cls
public with sharing class ContributorService {

    public static List<Contributor__c> getContributors() {

        return [
            SELECT Id,
                   Name,
                   Reputation_Score__c,
                   Total_Contributions__c,
                   Current_Rank__c
            FROM Contributor__c
        ];

    }

    public static void updateContributorReputation(Id contributorId, Integer points) {

        Contributor__c contributor = [

            SELECT Id,
                   Reputation_Score__c,
                   Total_Contributions__c,
                   Current_Rank__c

            FROM Contributor__c

            WHERE Id = :contributorId

            LIMIT 1

        ];

        if(contributor.Reputation_Score__c == null)
            contributor.Reputation_Score__c = 0;

        if(contributor.Total_Contributions__c == null)
            contributor.Total_Contributions__c = 0;

        contributor.Reputation_Score__c += points;
        contributor.Total_Contributions__c += 1;

        if(contributor.Reputation_Score__c >= 500){

            contributor.Current_Rank__c = 'Diamond';

        }
        else if(contributor.Reputation_Score__c >= 300){

            contributor.Current_Rank__c = 'Platinum';

        }
        else if(contributor.Reputation_Score__c >= 150){

            contributor.Current_Rank__c = 'Gold';

        }
        else if(contributor.Reputation_Score__c >= 50){

            contributor.Current_Rank__c = 'Silver';

        }
        else{

            contributor.Current_Rank__c = 'Bronze';

        }

        update contributor;

    }

public static List<Contributor__c> getTopContributors(){

    return [

        SELECT Id,
               Name,
               Reputation_Score__c,
               Total_Contributions__c,
               Current_Rank__c

        FROM Contributor__c

        ORDER BY Reputation_Score__c DESC

        LIMIT 10

    ];

}}