force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organization__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organization__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RepositoryTriggerHandler.cls
public with sharing class RepositoryTriggerHandler {

    public static void afterInsert(List<Repository__c> repositories) {

        updateStatistics(repositories);

    }

    public static void afterUpdate(
        List<Repository__c> repositories,
        Map<Id, Repository__c> oldMap
    ) {

        Set<Repository__c> reposToUpdate = new Set<Repository__c>();

        reposToUpdate.addAll(repositories);
        reposToUpdate.addAll(oldMap.values());

        updateStatistics(new List<Repository__c>(reposToUpdate));

    }

    public static void afterDelete(List<Repository__c> repositories){

        updateStatistics(repositories);

    }

    private static void updateStatistics(List<Repository__c> repositories){

        Set<Id> projectIds = new Set<Id>();
        Set<Id> organizationIds = new Set<Id>();

        for(Repository__c repo : repositories){

            if(repo.Project__c != null){

                projectIds.add(repo.Project__c);

            }

            if(repo.Organization__c != null){

                organizationIds.add(repo.Organization__c);

            }

        }

        for(Id projectId : projectIds){

            ProjectService.updateRepositoryCount(projectId);

        }

        for(Id organizationId : organizationIds){

            OrganizationService.updateRepositoryCount(organizationId);

        }

    }

}