force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Active_Contributors__c.field-meta.xml
<CustomField>
    <fullName>Active_Contributors__c</fullName>
    <label>Active Contributors</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Primary_Mentor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Mentor</label>
    <referenceTo>Mentor__c</referenceTo>
    <relationshipLabel>Organizations</relationshipLabel>
    <relationshipName>Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/Technology_Stack__c.field-meta.xml
<CustomField>
    <fullName>Technology_Stack__c</fullName>
    <label>Technology Stack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrganizationAPI.cls
@RestResource(urlMapping='/opencore/organizations/*')
global with sharing class OrganizationAPI {

    @HttpGet
    global static List<Organization__c> getOrganizations() {

        return [

            SELECT
                Id,
                Name,
                Description__c,
                Website__c,
                Active__c,
                Active_Contributors__c,
                Total_Repositories__c,
                Technology_Stack__c,
                Primary_Mentor__c

            FROM Organization__c

            ORDER BY Name

        ];

    }

}